import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import ConvexClientProvider from "@/providers/convex-client-provider";
import { Toaster } from "react-hot-toast";
import { SignedIn, SignedOut, SignIn } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Whatsapp Clone",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Default icon
    apple: "/favicon-apple.ico", // For Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


      <body className={inter.className} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            {/* Hiển thị giao diện đăng nhập nếu người dùng chưa đăng nhập */}
            <SignedOut>
              <div className="flex items-center justify-center min-h-screen">
                <div className=" shadow-lg rounded-lg p-8 max-w-md w-full">
                  <SignIn routing="hash" />
                </div>
              </div>
            </SignedOut>
            {/* Hiển thị nội dung chính nếu người dùng đã đăng nhập */}
            <SignedIn>
              <main>{children}</main>
              <Toaster />
            </SignedIn>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
